name: Print Env Variables PRODUCTION

on:
  push:
    branches: [main]

jobs:
  print_env_job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Executar Print Env Variables - PRODUCTION'
        uses: BrHCastroDev/print-env-action@v1
        with:
          environment: 'PRODUCTION'
